Feat/workshops modal confirmation
barteknr1/uwaga-smartfon pull request #119
Opened 2024-02-23 14:06 UTC by PiotrDrechsler

2024-02-23 17:17 UTC, Okazaki92 requested changes
mały rzecz do poprawy. Reszta Ok :D

2024-02-23 17:17 UTC, Okazaki92 commented on src/components/WorkshopsForm/WorkshopFormModalContent.jsx
> +  const {openModal, isModalVisible, setModalContent, setIsModalVisible} =
setIsModalVisible do wywalania zamiast tego closeModal

2024-02-23 17:17 UTC, Okazaki92 commented on src/components/WorkshopsForm/WorkshopFormModalContent.jsx
> +              setIsModalVisible(false)
tutaj zamiast tego setModalVisible musisz dać closeModal() bo w tej chwili jak klikniesz na buttona jednego albo drugiego to nie działa scroll strony

2024-02-23 17:17 UTC, Okazaki92 commented on src/components/WorkshopsForm/WorkshopFormModalContent.jsx
> +              setIsModalVisible(false)
j.w

2024-02-26 14:47 UTC, PiotrDrechsler commented on src/components/WorkshopsForm/WorkshopFormModalContent.jsx
> +  const {openModal, isModalVisible, setModalContent, setIsModalVisible} =
O faktycznie :D Teraz wszystko jest ok. Poprawione i śmiega. Merguje!

2024-02-26 14:48 UTC, merged