Feat/modal
barteknr1/uwaga-smartfon pull request #22
Opened 2024-01-03 11:38 UTC by barteknr1

2024-01-03 19:06 UTC, Okazaki92 commented
Branch ma konflikt danych więc trzeba zrobić synchro. Do tego w do klasy css.modal można dodać propsa który będzie można określić w nast komponencie żeby sobie ktoś mógł ostylowac wymiary jeśli trzeba

2024-01-03 19:08 UTC, Okazaki92 requested changes
Komentarz wcześniej napisałem

2024-01-03 22:45 UTC, barteknr1 commented
> Branch ma konflikt danych więc trzeba zrobić synchro. Do tego w do klasy css.modal można dodać propsa który będzie można określić w nast komponencie żeby sobie ktoś mógł ostylowac wymiary jeśli trzeba

No właśnie tu pytanie jakie style mają być zmieniane. To mocno wstępna wersja. Też się zastanawiam nad tym jakiego narzędzia użyć do open/close

2024-01-04 07:59 UTC, Okazaki92 commented
Zmieniać się może np padding albo jakiś gap między zawartością. Nie patrzyłem jeszcze dokładnie o ile się różnią modale.
Co do obsługi zamykania, to useState nie ogarnie tego?

2024-01-05 10:35 UTC, barteknr1 commented
Konflikty poprawione, poprawki będę wrzucał wraz z rozwojem reszty modali

2024-01-05 10:35 UTC, merged