Feat/be a volunteer
barteknr1/uwaga-smartfon pull request #33
Opened 2024-01-06 20:07 UTC by DagmaraSobczak

2024-01-07 15:36 UTC, barteknr1 requested changes
Póki co tylko svg do zmiany. Trzeba będzie też usunąć te paddingi, ale to po tym jak zrobimy porządek z sekcją i jej odstępami

2024-01-07 15:36 UTC, barteknr1 commented on src/assets/images/BeAVolunteer.png
Zrób z tego również svg

2024-01-09 23:32 UTC, Okazaki92 reviewed
Tego svg to przerzuć proszę do sprite.svg żeby w jednym miejscu były wszystkie svgi
Oraz punkty przełamania są inne dla tabletu i pc

2024-01-10 22:26 UTC, barteknr1 approved these changes

2024-01-10 22:27 UTC, merged