feat: VolunteeringAreas
barteknr1/uwaga-smartfon pull request #34
Opened 2024-01-06 22:50 UTC by Julia-Kaim

2024-01-07 13:57 UTC, barteknr1 requested changes

2024-01-07 13:57 UTC, barteknr1 commented on src/pages/Volunteering/Volunteering.jsx
> +      <VolunteeringAreas></VolunteeringAreas>
Jeżeli nie potrzebujesz niczego zagnieżdżać to używaj samozamykającego się komponentu np. `<VolunteeringAreas />`

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreas/VolunteeringAreas.jsx
> +import Img8 from '../../assets/VolunteeringAreas/Img8.png'
To powinny być ikony

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreas/VolunteeringAreas.module.css
> +.VolunteeringAreas {
Dorzuć do tej klasy `justify-content: center;`

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreasItem/VolunteeringAreasItem.jsx
> +          <img src={url} alt="VolunteeringAreasPhoto" />
Rozmiary tych obrazków się nie zgadzają. Alt nie może być wszędzie taki sam, ale jak to będą ikony to nie będzie wymagany :)

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreas/VolunteeringAreas.jsx
> +      <div className={styles.VolunteeringAreas}>
To aż się prosi, żeby zrobić listę `<ul>`.

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreasItem/VolunteeringAreasItem.module.css
> +  max-width: 230px;
Skąd jest te 230px?

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreasItem/VolunteeringAreasItem.jsx
> +          <span className={styles.VolunteeringAreasItem_ItemDescription}>
IMO lepszy byłby `<p>`

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreasItem/VolunteeringAreasItem.jsx
> +        <div className={styles.VolunteeringAreasItem_Item}>
Powtórzony Item w nazwie nie jest dobry

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreasItem/VolunteeringAreasItem.jsx
> +    <div>
Ten `<div>` można usunąć

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreas/VolunteeringAreas.module.css
> +  padding: 64px;
Ten padding można usunąć, powinien wychodzić z najwyższego kontenera w sekcji

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreas/VolunteeringAreas.module.css
> +  padding: 10px;
Po co jest ten padding? Skąd się wziął?

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreasItem/VolunteeringAreasItem.module.css
> +  background-color: var(--third-background-color);
Ten background-color jest niepotrzebny, masz go już w innym miejscu wyżej

2024-01-07 13:57 UTC, barteknr1 commented on src/components/VolunteeringAreasItem/VolunteeringAreasItem.module.css
> +  height: auto;
Niepotrzebne, auto jest defaultowe

2024-01-17 22:16 UTC, Okazaki92 commented
Ja myśle że tego pulla można usunąć bo już poszedł merge z całą sekcją

2024-01-18 21:27 UTC, closed without merging