feat/create newsletter section with styles for mobile and tablet
barteknr1/uwaga-smartfon pull request #35
Opened 2024-01-08 19:40 UTC by Okazaki92

2024-01-09 17:20 UTC, barteknr1 requested changes
Wygląda OK, ale mam kilka sugestii. Oprócz komentarzy możesz pousuwać te font-style: normal

2024-01-09 17:20 UTC, barteknr1 commented on src/assets/svg/sprite.svg
Mamy już plik z ikonami

2024-01-09 17:20 UTC, barteknr1 commented on src/components/Newsletter/Newsletter.module.css
> +.inputText {
Dodaj tutaj background-color: transparent

2024-01-09 17:20 UTC, barteknr1 commented on src/components/Newsletter/Newsletter.jsx
> +              <use href={sprite + '#trailing-icon'} />
Ta ikonka już jest jako icon-close, choć teraz uważam, że nazwa niekoniecznie pasuje do kasowania tekstu. Dodatkowo X się podświetla na fioletowo na :focus, a w figmie nie. Jest tylko efekt na :hover

2024-01-09 17:20 UTC, barteknr1 commented on src/components/Newsletter/Newsletter.jsx
> +          </blockquote>
`<blockquote>` używa się tylko do cytowanych tekstów. Użyłbym tutaj zwykłych paragraph

2024-01-09 17:20 UTC, barteknr1 commented on src/components/Newsletter/Newsletter.module.css
> +  font-style: normal;
Niepotrzebny font-style

2024-01-09 18:31 UTC, Okazaki92 commented on src/assets/svg/sprite.svg
ten plik sprite.svg już wcześniej dodałem, czy mam jakieś ikony przełożyć?

2024-01-09 19:17 UTC, barteknr1 commented on src/assets/svg/sprite.svg
Najlepiej aby wszystkie były w jednym miejscu

2024-01-09 19:36 UTC, Okazaki92 commented on src/assets/svg/sprite.svg
w icons.svg są 3 albo 4 ikony to może to lepiej przekleić??

2024-01-09 20:07 UTC, barteknr1 commented on src/assets/svg/sprite.svg
Masz rację :) Miałem na myśli to, że wszystkie ikony mają iść do sprite.svg. Również te z folderu AboutConference

2024-01-10 22:38 UTC, barteknr1 approved these changes

2024-01-10 22:39 UTC, merged