feat/ add section Workshops with styles for pc, tab, mobile
barteknr1/uwaga-smartfon pull request #44
Opened 2024-01-13 00:52 UTC by Okazaki92

2024-01-13 21:50 UTC, barteknr1 requested changes

2024-01-13 21:50 UTC, barteknr1 commented on src/components/Workshops/Workshops.jsx
> +            </p>
Ten `<p>` nie może znajdować się bezpośrednio pod `<ul>`. Zrób 2 `<div>`, w pierwszym będzie lewa strona, w drugim prawa.

2024-01-14 22:40 UTC, Okazaki92 commented on src/components/Workshops/Workshops.jsx
> +            </p>
Poprawione. Dzięki za przypomnienie o tym <p>

2024-01-15 19:00 UTC, PiotrDrechsler approved these changes
Na moje oko wszsytko ok.

2024-01-15 19:03 UTC, merged