feat/ added css style for mobile,tablet, desktop
barteknr1/uwaga-smartfon pull request #53
Opened 2024-01-18 16:14 UTC by DagmaraSobczak

2024-01-18 21:19 UTC, barteknr1 requested changes
Cześć, zaznaczyłem kilka rzeczy do poprawy. Dodatkowo text i dearVolunteerText również można połączyć w jedną klasę tak jak boxy.

2024-01-18 21:19 UTC, barteknr1 commented on src/components/DearVolunteer/DearVolunteer.jsx
> +      title="Szanowni wolontariusze ! "
Tych odstępów wokół wykrzyknika nie ma

2024-01-18 21:19 UTC, barteknr1 commented on src/components/DearVolunteer/DearVolunteer.module.css
> +  letter-spacing: 0.12%;
To nie zadziała

2024-01-18 21:19 UTC, barteknr1 commented on src/components/DearVolunteer/DearVolunteer.module.css
> +}
textBox1 i 2 się nie różnią za wyjątkiem align-items, które nic nie zmienia. Śmiało można połączyć to w jedną klasę.

2024-01-18 21:19 UTC, barteknr1 commented on src/components/DearVolunteer/DearVolunteer.jsx
> +            <p>
Tutaj brakuje klasy

2024-01-18 21:19 UTC, barteknr1 commented on src/components/DearVolunteer/DearVolunteer.jsx
> +            <p className={css.text}>
tej klasy nie ma w ogóle w css

2024-01-19 15:42 UTC, DagmaraSobczak commented on src/components/DearVolunteer/DearVolunteer.jsx
> +      title="Szanowni wolontariusze ! "
na mobilce jest, ok usuwam

2024-01-20 16:00 UTC, barteknr1 approved these changes

2024-01-20 16:00 UTC, merged