Fix/navigation
barteknr1/uwaga-smartfon pull request #62
Opened 2024-01-21 19:59 UTC by PiotrDrechsler

2024-01-23 10:59 UTC, Okazaki92 requested changes
W sumie tylko ta jedna poprawka.
BTW ten dropdown z poprzednimi edycjami też możesz już robić i w hrefie wrzucić linki do innych edycji :D

2024-01-23 10:59 UTC, Okazaki92 commented on src/components/NavHome/index.js
> +  },
pomiędzy brakuje odnośnika do Partnerzy & Patroni

2024-01-23 14:48 UTC, PiotrDrechsler commented on src/components/NavHome/index.js
> +  },
Ok dodane :D Dropdown z edycjami i zakotwiczenia zrobię jutro i cały navbar będzie gotowy :)

2024-01-24 18:17 UTC, barteknr1 approved these changes
Wstępnie jest ok tylko popraw konflikt. Fajnie by było jakbyś dorzucił zamykanie menu na kliknięcie poza nim :)

2024-01-24 18:18 UTC, barteknr1 requested changes
Wstępnie jest ok tylko popraw konflikt. Fajnie by było jakbyś dorzucił zamykanie menu na kliknięcie poza nim :)

2024-01-29 12:23 UTC, PiotrDrechsler reviewed
dodałem wyjaśnienia

2024-01-29 12:23 UTC, PiotrDrechsler commented on src/assets/svg/icon-burger.svg
Do usunięcia

2024-01-29 12:23 UTC, PiotrDrechsler commented on package.json
jak nikt nie używa tej biblioteki to jest do usunięcia

2024-01-29 12:23 UTC, PiotrDrechsler commented on src/components/NavHome/NavHome.jsx
zmieniłem nazwę komponentu na Nav bo udało mi się zrobić uniweralny kod dla całej nawigacji - dodałem tylko osbny blok do NavTablet

2024-01-29 12:23 UTC, PiotrDrechsler commented on src/components/Nav/Nav.module.css
.navItemIcon nie jest potrzebna

2024-01-29 12:23 UTC, PiotrDrechsler commented on src/components/SharedLayout/SharedLayout.jsx
Tutaj zmieniłem nazwy aby było bardziej zrozumiałem co do czego służy

2024-01-29 14:04 UTC, merged