feat/ add lastEdition section and Section component
barteknr1/uwaga-smartfon pull request #8
Opened 2023-12-22 03:38 UTC by Okazaki92

2023-12-22 17:13 UTC, barteknr1 requested changes
Cześć, ode mnie kilka uwag :)
GALLERY_GB wypadałoby zamienić na mniejsze litery.
Dodatkowo slider dziwnie przeskakuje co jakiś czas po załadowaniu strony. Czy u Ciebie jest tak samo?

2023-12-22 17:13 UTC, barteknr1 commented on src/components/LastEditions/LastEditions.jsx
> +import slider12 from '../../assets/images/slider/slider12.jpg'
Wrzuciłbym to pod jeden import.

2023-12-22 17:13 UTC, barteknr1 commented on src/components/LastEditions/LastEditions.jsx
> +                alt="Opis zdjęcia 1"
Alty do poprawienia

2023-12-22 17:13 UTC, barteknr1 commented on src/components/LastEditions/LastEditions.jsx
> +            </div>
To wszystko lepiej by było zrobić za pomocą map, żeby nie było tasiemca

2023-12-22 17:13 UTC, barteknr1 commented on src/components/LastEditions/LastEditions.jsx
> +const LastEditions = () => {
IMO lepsza nazwa byłaby PreviousEditions

2023-12-22 17:13 UTC, barteknr1 commented on src/components/LastEditions/LastEditions.jsx
> +        <div>
Te dwa `div` chyba nic nie zmieniają. Czy są potrzebne?

2023-12-22 17:24 UTC, Okazaki92 commented on src/components/LastEditions/LastEditions.jsx
> +                alt="Opis zdjęcia 1"
Tak alty wiem. Wczoraj już mi się nie chciało siedzieć 😁

2023-12-22 21:21 UTC, Okazaki92 commented
Hej pozmnieniałem wszystko stosując twoje uwagi i teraz powinno być dobrze, wymieniłem libke bo tamta coś nie chciała współpracować ta działa dużo lepiej (przynajmniej u mnie :D)

2023-12-23 12:28 UTC, barteknr1 approved these changes
Ok, na razie akceptuję. Te alty będzie trzeba poprawić tak aby były bardziej treściwe. Najlepiej zrobić jakąś tablicę obiektów z kluczem w postaci alt.

2023-12-23 12:29 UTC, merged